/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg6_carlosnuila;

import javax.swing.DefaultListModel;


/**
 *
 * @author Carlos Nuila
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearCriminal = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jb_crearCrim = new javax.swing.JButton();
        jt_nombreCriminal = new javax.swing.JTextField();
        sp_edad = new javax.swing.JSpinner();
        jt_numeroIdentidad = new javax.swing.JTextField();
        jt_numeroCelda = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jb_crearCriminal = new javax.swing.JButton();
        jb_crearDelito = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jb_eliminarCriminal = new javax.swing.JButton();
        jb_modificarCriminal = new javax.swing.JButton();
        jb_crearExpediente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jb_modificarDelito = new javax.swing.JButton();
        jb_verDelitos = new javax.swing.JButton();
        jb_eliminarDelito = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_listaCriminales = new javax.swing.JList<>();

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Crear Criminal");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Edad:");

        jLabel6.setText("Numero Identidad:");

        jLabel7.setText("Numero de Celda:");

        jLabel8.setText("Años por cumplir:");

        jb_crearCrim.setText("Crear Criminal");

        sp_edad.setModel(new javax.swing.SpinnerNumberModel(16, null, null, 1));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout jd_crearCriminalLayout = new javax.swing.GroupLayout(jd_crearCriminal.getContentPane());
        jd_crearCriminal.getContentPane().setLayout(jd_crearCriminalLayout);
        jd_crearCriminalLayout.setHorizontalGroup(
            jd_crearCriminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearCriminalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(jd_crearCriminalLayout.createSequentialGroup()
                .addGroup(jd_crearCriminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearCriminalLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jd_crearCriminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crearCriminalLayout.createSequentialGroup()
                                .addGroup(jd_crearCriminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_crearCriminalLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jd_crearCriminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_nombreCriminal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_crearCriminalLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jt_numeroCelda, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_crearCriminalLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_crearCriminalLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jt_numeroIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_crearCriminalLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jb_crearCrim)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jd_crearCriminalLayout.setVerticalGroup(
            jd_crearCriminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearCriminalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jd_crearCriminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jt_nombreCriminal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearCriminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearCriminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jt_numeroIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearCriminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jt_numeroCelda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jd_crearCriminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_crearCrim)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_crearCriminal.setText("Crear");
        jPanel1.add(jb_crearCriminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 100, 40));

        jb_crearDelito.setText("Crear");
        jPanel1.add(jb_crearDelito, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 100, 40));

        jLabel1.setText("Criminal:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jb_eliminarCriminal.setText("Eliminar");
        jPanel1.add(jb_eliminarCriminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 100, 40));

        jb_modificarCriminal.setText("Modificar ");
        jPanel1.add(jb_modificarCriminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 100, 40));

        jb_crearExpediente.setText("Crear Expediente");
        jPanel1.add(jb_crearExpediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 120, 40));

        jLabel2.setText("Delito:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jb_modificarDelito.setText("Modificar");
        jPanel1.add(jb_modificarDelito, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 110, 40));

        jb_verDelitos.setText("Ver Delitos");
        jPanel1.add(jb_verDelitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 100, 40));

        jb_eliminarDelito.setText("Eliminar");
        jPanel1.add(jb_eliminarDelito, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 110, 40));

        jl_listaCriminales.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_listaCriminales);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton jb_crearCrim;
    private javax.swing.JButton jb_crearCriminal;
    private javax.swing.JButton jb_crearDelito;
    private javax.swing.JButton jb_crearExpediente;
    private javax.swing.JButton jb_eliminarCriminal;
    private javax.swing.JButton jb_eliminarDelito;
    private javax.swing.JButton jb_modificarCriminal;
    private javax.swing.JButton jb_modificarDelito;
    private javax.swing.JButton jb_verDelitos;
    private javax.swing.JDialog jd_crearCriminal;
    private javax.swing.JList<String> jl_listaCriminales;
    private javax.swing.JTextField jt_nombreCriminal;
    private javax.swing.JTextField jt_numeroCelda;
    private javax.swing.JTextField jt_numeroIdentidad;
    private javax.swing.JSpinner sp_edad;
    // End of variables declaration//GEN-END:variables
}
